### PR TITLE
Fix move/rename operations

### PR DESCRIPTION
**Pull request by maksimru**
Fix for issue #55 
Existing version is totally broken on copy/move/rename operations

### CODE REVIEW

**Comment by jameslkingsley** [comment]
Can confirm this works!

**Comment by jameslkingsley** [comment]
@maksimru Is there a way to use this fork when using [laravel-google-cloud-storage](https://github.com/Superbalist/laravel-google-cloud-storage)? It requires this repository, however when I add the following to my composer file it doesn't pull in your fix.

```
"repositories": [
    {"type": "vcs", "url": "https://github.com/maksimru/flysystem-google-cloud-storage"}
]
```

**Comment by maksimru** [comment]
Please use this sample to pull fixed version:
composer.json:

```json
{
    "repositories": [{
            "type": "vcs",
            "url": "https://github.com/maksimru/laravel-google-cloud-storage.git"
        },
        {
            "type": "vcs",
            "url": "https://github.com/maksimru/flysystem-google-cloud-storage.git"
        },
    ],
    "require": {
        "superbalist/laravel-google-cloud-storage": "dev-master#3cb952fd4599f31bacdf36379703e85dbd0f6157",
        "superbalist/flysystem-google-storage": "dev-master#093b7e4b46f37720109e9efa594782cd0b3ced02"
    }
}
```

**Comment by jameslkingsley** [comment]
TravisCI build fixed in #61

**Pull request merged**
