### PR TITLE
Fix deleteDir

### PR DESCRIPTION
**Pull request by Yo1L**
A directory is not removed if we only delete the object directory.
We need to remove recursively all files and remove the directory itself !

### CODE REVIEW

**Comment by fgilio** [comment]
This PR fixes an important problem with the package, pls merge it

**Comment by nicja** [comment]
The tests for this are failing, we need someone to take a look before we can merge this

**Comment by jimmypuckett** [comment]
This is duplicated by #94. Given that the other MR has passing test.

I am with @fgilio in that this is important as it is the expected behavior given how the other drivers work.

Thanks!

**Comment by nicja** [comment]
Closed in favour of #94

**Pull request closed without merging**
